import Link from "next/link";
const instagram="https://www.instagram.com/empregosnv/";
const Arrow=()=> <span aria-hidden="true">↗</span>;
const Check=()=> <span className="check" aria-hidden="true">✓</span>;
function Brand({inverse=false}:{inverse?:boolean}){return <div className={`brand ${inverse?"inverse":""}`}><span className="brandSymbol"><b>N</b><i>V</i></span><span><strong>empregos</strong><small>NOVA VENÉCIA</small></span></div>}
const actions=[
 {n:"01",i:"◎",title:"Candidatos em busca de emprego",text:"Encontre profissionais da nossa cidade",href:"#candidatos",featured:true},
 {n:"02",i:"+",title:"Anunciar uma vaga",text:"Divulgação gratuita para empresas",href:"#anunciar"},
 {n:"03",i:"▤",title:"Criar meu Currículo Aprovado",text:"Profissional + 1 ano no Portal",href:"/curriculo"},
 {n:"04",i:"◆",title:"Divulgar minha empresa",text:"Sua marca em evidência toda semana",href:"#empresas"},
];
export default function Home(){return <main>
 <header className="topbar"><a href="#inicio" aria-label="Início"><Brand/></a><a className="headerCta" href={instagram} target="_blank" rel="noreferrer">Falar com a equipe <Arrow/></a></header>
 <section className="hero" id="inicio"><div className="heroPattern">NV</div><div className="heroIntro"><span className="kicker light"><i/> NOVA VENÉCIA • ES</span><h1>Conexões locais.<br/><em>Oportunidades reais.</em></h1><p>Encontre profissionais, anuncie vagas, fortaleça seu currículo ou apresente sua empresa para quem vive e trabalha na nossa cidade.</p><a className="textLink" href="#acessos">Escolha o que você precisa ↓</a></div><div className="actionPanel" id="acessos"><div className="panelHead"><strong>Como podemos ajudar?</strong><span>ACESSO RÁPIDO</span></div>{actions.map(a=><a className={`actionCard ${a.featured?"featured":""}`} href={a.href} key={a.n}><span className="actionNumber">{a.n}</span><span className="actionIcon">{a.i}</span><span className="actionCopy"><b>{a.title}</b><small>{a.text}</small></span><Arrow/></a>)}</div></section>
 <section className="cvSpotlight" id="curriculo"><div><span className="kicker"><i/> PARA QUEM BUSCA OPORTUNIDADE</span><h2>Um currículo que<br/><em>abre portas.</em></h2><p>Não é só um arquivo bonito. É uma apresentação profissional clara, fácil de ler e preparada para mostrar o seu valor — com divulgação no Portal Empregos NV por 1 ano.</p><div className="pills"><span><Check/> Revisado e organizado</span><span><Check/> Entregue em até 48h</span><span><Check/> 1 ano no Portal</span></div><Link className="button" href="/curriculo">Conhecer o Currículo Aprovado <Arrow/></Link></div><aside className="priceCard"><span>SERVIÇO CARRO-CHEFE</span><small>INVESTIMENTO ÚNICO</small><div className="price"><sup>R$</sup>49<em>,90</em></div><p>Menos de <b>R$ 0,14 por dia</b> durante o ano em que seu currículo fica divulgado no Portal.</p><Link href="/curriculo">Ver tudo que está incluso <Arrow/></Link></aside></section>
 <section className="section candidates" id="candidatos"><div className="sectionTitle"><span className="kicker"><i/> BANCO DE TALENTOS LOCAL</span><h2>Pessoas prontas para trabalhar.<br/><em>Perto da sua empresa.</em></h2><p>Conheça candidatos de Nova Venécia que investiram na própria apresentação e estão em busca de uma oportunidade.</p></div><div className="portalMock"><div className="filters"><span>Todos os perfis</span><span>Administrativo</span><span>Comercial</span><span>Serviços</span></div><div className="profiles">{[["AM","Auxiliar administrativo"],["CV","Atendimento e vendas"],["JS","Serviços gerais"]].map(x=><article key={x[0]}><span>{x[0]}</span><div><b>{x[1]}</b><small>Nova Venécia • Disponível</small></div><i>PERFIL VERIFICADO</i></article>)}</div><p>Prévia conceitual. Perfis reais serão publicados com autorização.</p></div><a className="button outline" href={instagram} target="_blank" rel="noreferrer">Quero encontrar candidatos <Arrow/></a></section>
 <section className="employer" id="anunciar"><div><span className="kicker light"><i/> OFERTA PARA EMPRESAS</span><h2>Tem uma vaga?<br/><em>Anuncie grátis.</em></h2><p>Envie as informações pelo Direct. Organizamos a oportunidade e divulgamos para o público local sem cobrar pela publicação da vaga.</p><div className="dataList">{['Nome da empresa','Nome da vaga','Salário e benefícios','Pré-requisitos','Contato para candidatura'].map((x,i)=><span key={x}><b>{String(i+1).padStart(2,'0')}</b>{x}</span>)}</div><a className="button green" href={instagram} target="_blank" rel="noreferrer">Anunciar vaga gratuitamente <Arrow/></a></div><aside><span>GRÁTIS</span><h3>Uma boa contratação começa com uma vaga bem apresentada.</h3><p>Você fornece os dados. O Empregos NV transforma a informação em uma comunicação clara e local.</p><small>Sem assinatura • Atendimento pelo Direct</small></aside></section>
 <section className="section business" id="empresas"><div className="sectionTitle"><span className="kicker"><i/> EMPRESAS E PRESTADORES</span><h2>Sua empresa lembrada.<br/><em>Toda semana.</em></h2><p>Apresente produtos e serviços em Reels, carrossel ou Story para um público local que já acompanha o Empregos NV.</p></div><div className="plans"><article className="recommended"><span className="tag">MELHOR CUSTO-BENEFÍCIO</span><small>PARCERIA DE 6 MESES</small><h3>Presença constante</h3><div className="planPrice"><sup>R$</sup>249<em>,00</em><small>/mês</small></div><ul><li><Check/>1 divulgação por semana</li><li><Check/>Reels, carrossel ou Story</li><li><Check/>Produtos ou serviços em evidência</li><li><Check/>Planejamento de presença local</li></ul><a className="button green" href={instagram} target="_blank" rel="noreferrer">Quero fechar 6 meses <Arrow/></a></article><article><small>PLANO MÊS A MÊS</small><h3>Mais flexibilidade</h3><div className="planPrice"><sup>R$</sup>299<em>,00</em><small>/mês</small></div><ul><li><Check/>1 divulgação por semana</li><li><Check/>Reels, carrossel ou Story</li><li><Check/>Alcance do público local</li><li><Check/>Sem compromisso de 6 meses</li></ul><a className="button outline" href={instagram} target="_blank" rel="noreferrer">Contratar plano mensal <Arrow/></a></article></div></section>
 <section className="closing"><Brand inverse/><h2>Nova Venécia trabalha melhor<br/>quando as pessoas certas se encontram.</h2><p>Empregos NV — a ponte local entre talentos, oportunidades e empresas.</p><a className="button green" href={instagram} target="_blank" rel="noreferrer">Falar com @empregosnv <Arrow/></a></section>
 <footer><Brand inverse/><p>Empregos NV — conectando pessoas e oportunidades.</p><span>Nova Venécia • Espírito Santo</span></footer>
 </main>}
