import type {Metadata} from "next";import Link from "next/link";
const instagram="https://www.instagram.com/empregosnv/";const Check=()=> <span className="check">✓</span>;const Arrow=()=> <span>↗</span>;
export const metadata:Metadata={title:"Currículo Aprovado | Empregos NV",description:"Currículo profissional, entrega em até 48 horas, 3 Stories e 1 ano no Portal Empregos NV por R$ 49,90."};
export default function Curriculo(){return <main className="salesPage">
 <header className="salesHeader"><Link href="/">← Empregos NV</Link><a href={instagram} target="_blank" rel="noreferrer">Atendimento pelo Direct <Arrow/></a></header>
 <section className="salesHero"><div><span className="kicker light"><i/> CURRÍCULO APROVADO</span><h1>Você tem experiência.<br/>Seu currículo precisa <em>mostrar isso.</em></h1><p>Transformamos suas informações em uma apresentação profissional, clara e fácil de entender — e divulgamos seu currículo por 1 ano no Portal Empregos NV.</p><div className="salesProof"><span><Check/> Entrega em até 48 horas</span><span><Check/> 3 Stories de divulgação</span><span><Check/> 1 ano no Portal</span></div><a className="button green" href={instagram} target="_blank" rel="noreferrer">Quero meu Currículo Aprovado <Arrow/></a><small>Pagamento via PIX ou cartão • Atendimento pelo Direct</small></div><aside className="salesPrice"><span>INVESTIMENTO ÚNICO</span><div><sup>R$</sup>49<em>,90</em></div><p>O equivalente a</p><strong>R$ 4,16 por mês</strong><small>considerando os 12 meses de divulgação no Portal</small></aside></section>
 <section className="salesSection why"><div className="sectionTitle"><span className="kicker"><i/> POR QUE ISSO IMPORTA</span><h2>Um bom currículo reduz a dúvida de quem contrata.</h2><p>Na seleção, clareza facilita a decisão. Quando cargo, experiências e habilidades aparecem na ordem certa, o recrutador entende mais rápido onde você pode contribuir.</p></div><div className="scienceGrid"><article><b>01</b><h3>Leitura fácil</h3><p>Hierarquia visual e textos objetivos diminuem o esforço necessário para encontrar suas informações principais.</p></article><article><b>02</b><h3>Valor percebido</h3><p>Organização, revisão e consistência transmitem preparo antes mesmo da primeira conversa.</p></article><article><b>03</b><h3>Mais exposição local</h3><p>Você não depende apenas de enviar o PDF: seu perfil permanece disponível no Portal durante 1 ano.</p></article></div></section>
 <section className="comparison"><div><span className="kicker light"><i/> NÃO É SÓ UM PDF</span><h2>Um serviço completo para você ser <em>visto e compreendido.</em></h2><p>O Currículo Aprovado combina apresentação profissional com divulgação local. Você recebe um documento pronto para enviar e continua encontrável por empresas da região.</p></div><aside><span>VOCÊ RECEBE</span><ul><li><Check/><div><b>Currículo profissional em PDF</b><small>Visual limpo, organizado e pronto para enviar.</small></div></li><li><Check/><div><b>Revisão e valorização</b><small>Conteúdo estruturado para destacar seu potencial.</small></div></li><li><Check/><div><b>Entrega em até 48 horas</b><small>Após pagamento e recebimento dos dados.</small></div></li><li><Check/><div><b>Divulgação em 3 Stories</b><small>Visibilidade imediata no Empregos NV.</small></div></li><li><Check/><div><b>1 ano no Portal</b><small>Seu perfil disponível para empresas locais.</small></div></li></ul></aside></section>
 <section className="value"><div><span>FAÇA A CONTA</span><h2>R$ 49,90 por tudo isso.</h2><p>Durante 365 dias de presença no Portal, o investimento representa menos de <strong>R$ 0,14 por dia.</strong> É uma pequena decisão que melhora como você se apresenta nas próximas oportunidades.</p><a className="button" href={instagram} target="_blank" rel="noreferrer">Contratar agora pelo Direct <Arrow/></a></div><div className="timeline"><article><b>1</b><div><h3>Você chama no Direct</h3><p>Nós orientamos quais informações enviar.</p></div></article><article><b>2</b><div><h3>Pagamento e produção</h3><p>PIX ou cartão. Entrega em até 48 horas.</p></div></article><article><b>3</b><div><h3>Currículo pronto e divulgado</h3><p>PDF, 3 Stories e 1 ano no Portal.</p></div></article></div></section>
 <section className="salesSection faq"><div className="sectionTitle"><span className="kicker"><i/> DÚVIDAS RÁPIDAS</span><h2>Antes de contratar</h2></div><div className="faqGrid"><article><h3>Preciso já ter currículo?</h3><p>Não. Você envia suas informações e nós organizamos tudo desde o início.</p></article><article><h3>Em quanto tempo fica pronto?</h3><p>Em até 48 horas após o pagamento e recebimento dos dados completos.</p></article><article><h3>Onde será divulgado?</h3><p>Em 3 Stories e no Portal de candidatos do Empregos NV por 1 ano.</p></article><article><h3>Posso pagar com cartão?</h3><p>Sim. O pagamento pode ser feito via PIX ou cartão de crédito.</p></article></div></section>
 <section className="salesClosing"><span>CURRÍCULO APROVADO</span><h2>Sua próxima oportunidade pode começar com uma apresentação melhor.</h2><p>Invista R$ 49,90 em um currículo profissional e permaneça visível no Portal Empregos NV por 1 ano.</p><a className="button green" href={instagram} target="_blank" rel="noreferrer">Quero contratar agora <Arrow/></a><Link href="/">← Voltar para o site</Link></section>
 <div className="mobileSticky"><div><small>CURRÍCULO APROVADO</small><b>R$ 49,90</b></div><a href={instagram} target="_blank" rel="noreferrer">Contratar <Arrow/></a></div>
 </main>}
